- src/cpp/Exception.h
- src/cpp/OpenWsmanClient.cpp
- src/cpp/WsmanClient.h
I added **WsmanResourceNotFound** class for better error handling. Current source code doesn't inform the client about an error, if some resouce can't be found; *nothing happens*.
> introduce WsmanResourceNotFound exception for enumeration

- README.md
Due to missing empty lines around the commands in build instruction section, those commands are squashed into single line during conversion to show README on the GitHub project page.
> fix markdown syntax in README.md

- autoconfiscate.sh
Print the error/warning message to standard error and require the user of the script to pass an additional argument to get past the warning message, making it clearer that the autotools build system is deprecated and building with CMake is strongly preferred.
This is a follow-up to #88.
New standard behavior (exits with a non-zero exit code):
```
$ ./autoconfiscate.sh
*** Autoconf/automake is deprecated for Openwsman and might not fully work.
*** Please use CMake instead!
*** To ignore this warning and proceed regardless, re-run as follows:
***   ./autoconfiscate.sh --ignore-deprecation-warning
```
If invoked with the option, will still print the first part of the message and then proceed as before.
> Make deprecation of autoconf/automake more visible

- src/server/wsmand-listener.c
Openwsman randomly crashes with BT like:
#0  0x00007f95523a45f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f95523a5ce8 in __GI_abort () at abort.c:90
#2  0x00007f954decc208 in rb_bug (fmt=fmt@entry=0x7f954e012ebf "Segmentation fault") at error.c:314
#3  0x00007f954df795b6 in sigsegv (sig=<optimized out>, info=<optimized out>, ctx=<optimized out>) at signal.c:679
#4  <signal handler called>
#5  freelist_extract (for_read=for_read@entry=1, sz=sz@entry=17736, ctx=<optimized out>, ctx=<optimized out>) at s3_both.c:701
#6  0x00007f955316c373 in ssl3_setup_read_buffer (s=s@entry=0x7f9555886df0) at s3_both.c:770
#7  0x00007f955316c4d9 in ssl3_setup_buffers (s=0x7f9555886df0) at s3_both.c:827
#8  0x00007f955316da7d in ssl23_get_client_hello …
> Fix SSL library usage is not thread safe

- src/server/shttpd/defs.h
- src/server/shttpd/shttpd_config.h
I just noticed that one header file for shttpd is missing (because its name was "config.h", included in .gitignore). This commit fixes it and renames the header to make it less confusing.
> Add missing shttpd header file

- src/server/shttpd/shttpd.c
According to manpage:
>     RETURN VALUES
>            SSL_CTX_set_cipher_list() and SSL_set_cipher_list() return
>            1 if any cipher could be selected and 0 on complete failure.
return code '1' is the one that is documented as expected.
> Expect 1 from SSL_CTX_set_cipher_list(), not 0

- include/u/libu.h
- include/u/os.h
- src/cpp/OpenWsmanClient.cpp
- src/lib/u/iniparser.c
- src/lib/u/uuid.c
- src/lib/wsman-client.c
- src/lib/wsman-curl-client-transport.c
- src/lib/wsman-soap-envelope.c
- src/lib/wsman-xml.c
The sprintf, strcpy and such are banned from usage by security practices.
Replace them with more secure equivalents.
> Replace problematic string functions

- src/lib/u/debug.c
Check pointers returned from *strdup* functions for NULL
and return early in that case to avoid NULL dereferencing.
> debug: account for null from strdup

- bindings/wsman-client_opt.i
- include/wsman-client-api.h
- src/lib/wsman-client.c
flags variable is unsigned long, but all accessors are unsigned int.
Update accessors to unsigned long to eliminate type size
incompatibility problems.
> wsman-client: fix action options accessors

- src/lib/wsman-xml-serialize.c
Protect library from rouge input by checking that
received time values ares inside the standard bounds:
https://pubs.opengroup.org/onlinepubs/007908799/xsh/time.h.html
> wsman-xml-serialize: check parsed time for validity

- CMakeLists.txt
MSVC by default links against dynamic runtime library,
add option to link against static runtime.
> Add option to compile with msvc static runtime

- src/lib/wsman-client.c
Check existence of delivery_username instead of check
for delivery_password twice.
> wsman-client: check existence of delivery_username

- src/lib/wsman-soap-envelope.c
> wsman-soap-envelope: fix potential NULL pointer dereference

- include/u/memory.h
- src/lib/u/memory.c
- src/lib/wsman-client-transport.c
- src/lib/wsman-client.c
- src/lib/wsman-win-client-transport.c
Secure cleanup connection and proxy passwords after the last use to
eliminate possibility of password leak on memory release.
> openwsman: cleanup password after use

- src/lib/wsman-curl-client-transport.c
The wsmancli returns an error immediately after receiving
an HTTP 401 Unauthorized response.
The handling of authentication should be improved to better
conform to RFC 2616.
Author of the patch:
Thomas Derr (DFS Deutsche Flugsicherung GmbH, https://www.dfs.de/)
> Improve handling of HTTP 401 Unauthorized

- src/lib/wsman-win-client-transport.c
Free allocated memory in error path.
> openwsman: wsman-win-client-transport: plug leak in error path

- src/lib/u/iniparser.c
Account for column size in buffer.
Fix gcc warning:
openwsman/src/lib/u/iniparser.c: In function ‘iniparser_new’:
openwsman/src/lib/u/iniparser.c:503:50: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
503 |         snprintf(longkey, sizeof(longkey), "%s:%s", sec, key);
|                                                  ^
In file included from /usr/include/stdio.h:867,
from openwsman/src/lib/u/iniparser.c:31:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 2 and 2050 bytes into a destination of size 2049
> openwsman: iniparser: fix buffer size

- src/lib/wsman-win-client-transport.c
Initialize the certificate pointer to NULL to avoid
warnings about uninitilized variable usage that became
errors with new Visual Studio.
> openwsman: wsman-win-client-transport: initialize certificate pointer

- src/lib/wsman-client.c
Bail out if service functions return NULL pointers
to avoid NULL dereference.
> openwsman: wsman-client: add NULL checks

- src/plugins/swig/src/target_ruby.c
RARRAỲ_LEN and RARRAY_PTR work on VALUE, not rb_ary pointer.
> Fix Ruby array casts

- src/server/shttpd/shttpd.c
> call setgroups before setuid or setgid

- src/lib/u/memory.c
Fix order of parameters passed to memset.
> openwsman: fix memory cleanup

- README.testing
Make clear that LD_LIBRARY_PATH must be set when running tests from local (build) directory,
> set LD_LIBRARY_PATH for tests

- bindings/python/CMakeLists.txt
* Also removes EOL 3.x versions of Python
A couple questions:
* Python 3.7 EOL's in less than four months. Should we remove that too?
* Do we also want to remove all 2.x references?
This work was sponsored by https://metify.io
> Adds Python 3.11 support

- src/cpp/Exception.h
- src/cpp/WsmanClient.h
- src/cpp/WsmanEPR.h
- src/cpp/WsmanFilter.h
- src/cpp/WsmanOptions.h
- src/lib/wsman-client.c
- src/lib/wsman-epr.c
- src/lib/wsman-soap-envelope.c
- src/lib/wsman-xml.c
Fix part of "signed/unsigned mismatch" warnings.
Specialize "using namespace std;" to ensure c++17 compatibility.
> Fix warnings and c++17 compatibility

- src/lib/wsman-win-client-transport.c
Ignore more problematic certificates if verify_peer is 0.
> wsman-win-client-transport: add SECURITY_FLAG_IGNORE_CERT_WRONG_USAGE

- bindings/openwsman.i
openwsman fails to build with GCC 14:
```
cd /builddir/build/BUILD/openwsman-2.7.2/build/bindings/ruby && /usr/bin/gcc -Drbwsman_EXPORTS -I/builddir/build/BUILD/openwsman-2.7.2/build -I/usr/include/x86_64-linux -I/builddir/build/BUILD/openwsman-2.7.2/build/bindings/ruby -I/builddir/build/BUILD/openwsman-2.7.2 -I/builddir/build/BUILD/openwsman-2.7.2/bindings -I/builddir/build/BUILD/openwsman-2.7.2/include -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables …
```
> Fix incompatible pointer type error with GCC 14.

- include/Makefile.am
- src/lib/u/iniparser.c
- src/lib/wsman-cimindication-processor.c
- src/lib/wsman-event-pool.c
- src/lib/wsman-libxml2-binding.c
- src/lib/wsman-soap-message.c
- src/lib/wsman-soap.c
- src/lib/wsman-subscription-repository.c
- src/lib/wsman-xml-serialize.c
- src/lib/wsman-xml.c
See commit log.  The applied changes were necessary to allow building on my M2 with Mac OS using the default toolchain.
> Fixed prototypes, added a missing header to the install rule, and removed an unused variable.

- src/plugins/swig/src/target_ruby.c
Fixes:
/builddir/build/BUILD/openwsman-2.7.2-build/openwsman-2.7.2/src/plugins/swig/ruby/../src/../src/target_ruby.c: In function ‘RbGlobalInitialize’:
/builddir/build/BUILD/openwsman-2.7.2-build/openwsman-2.7.2/src/plugins/swig/ruby/../src/../src/target_ruby.c:136:14: error: passing argument 1 of ‘rb_protect’ from incompatible pointer type [-Wincompatible-pointer-types]
136 |   rb_protect(load_module, Qnil, &error);
|              ^~~~~~~~~~~ 
|              |
|              VALUE (*)(void) {aka long unsigned int (*)(void)}
In file included from /usr/include/ruby/internal/scan_args.h:38,
from /usr/include/ruby/ruby.h:46:
/usr/include/ruby/internal/intern/proc.h:349:26: note: expected ‘VALUE (*)(VALUE)’ {aka ‘long unsigned int (*)(long unsigned int)’} but argument is of type ‘VALUE …
> Fix to build with GCC 15.
