Openwsman/openwsman

src/cpp/OpenWsmanClient.cpp

don't generalize WsmanResourceNotFound

---

src/cpp/OpenWsmanClient.cpp
src/cpp/OpenWsmanClient.h

Fix typo and method semantics.

fix Windows OpenWsmanClient::SetClientCert()

---

src/lib/u/iniparser.c

Hi Klaus,
It seems that functions strlwc and strcrop are not thread-safe. Let's analyze function 
static char * strlwc(char * s)
{
static char l[ASCIILINESZ+1];
int i ;
if (s==NULL) return NULL ;
memset(l, 0, ASCIILINESZ+1);
i=0 ;
while (s[i] && i<ASCIILINESZ) {
l[i] = (char)tolower((int)s[i]);
i++ ;
}
l[ASCIILINESZ]=(char)0;
return l ;
}
This function can be called concurrently (at the same time) by more than one thread. The flow for every thread is as follow:
wsman_send_request
|->wsmc_handler(cl, request, NULL);
|->init_curl_transport(cl);
|->iniparser_getint(ini, "client:curlopt_nosignal", 0)
|->iniparser_getstring(d, key, INI_INVALID_KEY)
|->lc_key = strdup(strlwc(key))
As you can see it may happen that two threads in the same time can call function strlwc so they can modify static …

Removed static array from functions strlwc, strcrop to make them thread-safe.

---

bindings/wsman-client_opt.i
include/wsman-client-api.h
src/lib/wsman-client.c

Added 'add_property_array_item' native function for adding array items successively.

fixing #95

---

include/u/carpal.h
include/u/debug_internal.h
src/lib/u/debug.c
src/lib/u/uri.c
src/server/shttpd/shttpd.c
src/server/wsmand.c

Split up fixes from SLES patches.
These are mostly independent of each other, but since these mostly touch the same file, then only one pull request to avoid merge issues.

Fixes from SLES

---

examples/serialize.c
include/wsman-xml-api.h
src/cpp/OpenWsmanClient.cpp
src/lib/u/hash.c
src/lib/u/iniparser.c
src/lib/u/uoption.c
src/lib/u/uri.c
src/lib/wsman-client.c
src/lib/wsman-debug.c
src/lib/wsman-dispatcher.c
src/lib/wsman-epr.c
src/lib/wsman-faults.c
src/lib/wsman-filter.c
src/lib/wsman-libxml2-binding.c
src/lib/wsman-soap-envelope.c
src/lib/wsman-soap-message.c
src/lib/wsman-soap.c
src/lib/wsman-subscription-repository.c
src/lib/wsman-win-client-transport.c
src/lib/wsman-xml.c
src/server/wsmand-daemon.c

This is an assortment of different fixes for potential NULL de-reference issues.
Most of the issues are found by static analyzers and manual code review.

Potential NULL dereference issue fixes

---

src/lib/wsman-curl-client-transport.c
src/lib/wsman-faults.c
src/lib/wsman-soap-envelope.c

Fix usage of errorcodes from wrong enums and fix fault translation table.

Fix errorcodes

---

src/cpp/WsmanOptions.cpp
src/lib/wsman-client.c
src/lib/wsman-soap-envelope.c
src/server/wsmand-listener.c

NULL pointers and other assorted fixes

Miscellaneous fixes

---

src/cpp/OpenWsmanClient.cpp
src/lib/u/debug.c
src/lib/wsman-client.c
src/lib/wsman-soap-envelope.c
src/lib/wsman-soap.c

Put back accidentally removed string and miscellaneous fixes missed in previous MR

Followup fixes

---

include/wsman-client-api.h
include/wsman-client.h
src/cpp/OpenWsmanClient.cpp
src/cpp/OpenWsmanClient.h
src/cpp/WsmanClient.h
src/lib/wsman-client.c
src/lib/wsman-curl-client-transport.c

Fixes #131 
The C++ API is changed in this PR, so it need an API version bump.

Disable 100-continue conditionally

---

include/u/debug_internal.h
include/u/gettimeofday.h
include/u/os.h
include/u/pthreadx.h
include/wsman-client-api.h
include/wsman-xml-serializer.h
src/lib/u/buf.c
src/lib/u/hash.c
src/lib/u/lock.c
src/lib/u/log.c
src/lib/u/memory.c
src/lib/u/misc.c
src/lib/u/os.c
src/lib/u/uri.c
src/lib/u/uuid.c
src/lib/wsman-curl-client-transport.c
src/lib/wsman-debug.c
src/lib/wsman-xml-serialize.c

Let the client cross compile under Linux with MinGW for Windows.
This closes #147.

Enable cross compilation with MinGW

---

bindings/ruby/helpers.h

fix Ruby bindings for swig 4.1

---

bindings/ruby/helpers.h

fix function args for rb_hash_foreach

---

package/openwsman.spec.in

Enable cunit tests

---

ChangeLog
package/openwsman.spec.in

Prep for 2.7.2 release

---

CMakeLists.txt

Check for cunit header if BUILD_CUNIT_TESTS is enabled

---

package/openwsman.spec.in

BuildRequire cunit-devel in spec file

---

bindings/openwsman.i
bindings/ruby/openwsman/openwsman.rb
package/openwsman.rpmlintrc
package/openwsman.spec.in
src/server/shttpd/shttpd.c

Mostly compiler and rdoc warnings

Reduce build warnings

---

wsman_config.h.cmake

wsman_config.h.cmake: drop HAVE_CUNIT_BASIC_H

---

src/authenticators/file/file_auth.c

assume server runs from / dir

---

bindings/python/CMakeLists.txt

Python's driving me crazy

---

package/openwsman.rpmlintrc

please the rpm linter

---

ChangeLog

ChangeLog for 2.7.2 release

---

README.testing

set LD_LIBRARY_PATH for tests

---

src/lib/u/lock.c
src/lib/wsman-xml-serialize.c

Cleanup lock/unlock in xml serializer

---

src/cpp/OpenWsmanClient.cpp
src/cpp/OpenWsmanClient.h
src/lib/wsman-win-client-transport.c

Add explicit method in cpp interface to allow self-signed certificates.

Topic allow self signed cpp

---

CMakeLists.txt
package/openwsman.spec.in

3.12 is the one that introduced FindPython

LMS: openwsman: revert minimal cmake to 3.12
